### ISSUE TITLE
Build Issue with Push Plugin

### ISSUE THREAD

**Issue by nehil** [MaginSoft/MFileChooser#12]
Whenever I try Filechooser plugin with  [Cordova push Plugin](https://github.com/phonegap/phonegap-plugin-push) build fails. 

Following error I encounter :-

```
:generateDebugResources
:mergeDebugResourcesAAPT err(Facade for 15500028): C:\MyApps\Impalz\platforms\an
droid\res\drawable\divider_line_grey.png: libpng warning: iCCP: Not recognizing
known sRGB profile that has been edited
AAPT err(Facade for 3737552): C:\MyApps\Impalz\platforms\android\res\drawable-md
pi\apk.png: libpng warning: iCCP: Not recognizing known sRGB profile that has be
en edited

:processDebugManifest
:processDebugResources
:generateDebugSources
:compileDebugJavaWithJavacNote: Some input files use or override a deprecated AP
I.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

:compileDebugNdk UP-TO-DATE
:compileDebugSources
:transformClassesWithDexForDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/acce
ssibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionI
mpl;
 FAILED
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:50
4)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)



FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.pro
cess.ProcessException: org.gradle.process.internal.ExecException: Process 'comma
nd 'C:\Program Files\Java\jdk1.8.0_73\bin\java.exe'' finished with non-zero exit
 value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 8.257 secs
ERROR building one of the platforms: Error code 1 for command: cmd with args: /s
,/c,"C:\MyApps\Impalz\platforms\android\gradlew cdvBuildDebug -b C:\MyApps\Impal
z\platforms\android\build.gradle -Dorg.gradle.daemon=true -Pandroid.useDeprecate
dNdk=true"
You may not have the required environment or OS to build this project
Error: Error code 1 for command: cmd with args: /s,/c,"C:\MyApps\Impalz\platform
s\android\gradlew cdvBuildDebug -b C:\MyApps\Impalz\platforms\android\build.grad
le -Dorg.gradle.daemon=true -Pandroid.useDeprecatedNdk=true"
```
 
On removing plugin everything works perfectly. Also same issue goes with [Cordova facebook Plugin](https://github.com/jeduan/cordova-plugin-facebook4)

**Comment by gigioSouza** [comment]
I had that same issue with the Facebook plugin.
Take a look at [https://github.com/Wizcorp/phonegap-facebook-plugin/issues/1095](https://github.com/Wizcorp/phonegap-facebook-plugin/issues/1095), it helped me solve it.

**Comment by nehil** [comment]
I am already using facebook4 plugin and push plugin together But when I add Filechooser Build fails
